// src/components/about.svelte
<script>
	import { onMount } from 'svelte';

	import { typewriter } from '$lib/helpers/animations';

	let typeOccupation = false;
	let showOccupation = false;
	const colors = ['red', 'yellow', 'green'];

	onMount(() => (typeOccupation = true));
</script>

<div class="about-container">
	<div class="console-top">
		{#each colors as color}
			<div class="{color}-button fake-icon" />
		{/each}
	</div>
	<ul class="console-bottom">
		<li class="resume" key={'resume'}>
			<div class="resume input">
				<span class="arrow">></span>David.resume
			</div>
			<div class="resume output">
				<a href="/resume">Resume</a>
			</div>
		</li>

		<li class="education" key={'education'}>
			<div class="education input">
				<span class="arrow">></span>David.education
			</div>
			<div class="education output">
				[" B.A. Geography - University of California Los Angeles", "Self Study - App Academy Full
				Stack Bootcamp"]
			</div>
		</li>

		<li class="tech" key={'tech'}>
			<div class="tech input">
				<span class="arrow">></span>David.techStack
			</div>
			<div class="tech output">
				["HTML", "CSS", "Javascript", "Typescript", "React", "Redux", "Node", "PostgreSQL",
				"Docker", "AWS", "Python", "Ruby", "Rails", "GIS"]
			</div>
		</li>

		<li class="interests" key={'interests'}>
			<div class="interests input">
				<span class="arrow">></span>David.interests
			</div>
			<div class="interests output">
				["Skateboarding", "Rock Climbing", "League of Legends", "Running"]
			</div>
		</li>

		<li class="contact-info">
			<div class="contact-info input">
				<span class="arrow">></span>David.contactInfo
			</div>
			<div class="contact-info output">
				["
				<a href="mailto:me@daviddixon.io" target="_blank" alt="email address" rel="noopener">
					me@daviddixon.io
				</a>
				", "
				<a
					href="https://www.linkedin.com/in/david-d-b36589190/"
					target="_blank"
					alt="linkedin link"
					rel="noopener"
				>
					LinkedIn
				</a>
				", "
				<a
					href="https://github.com/chimichanga-dd"
					target="_blank"
					alt="github link"
					rel="noopener"
				>
					GitHub
				</a>
				"]
			</div>
		</li>
		<li class="occupation" key={'occupation'}>
			<div class="occupation input">
				<span class="arrow">></span><span>
					{#if typeOccupation}
						<span
							transition:typewriter={{ speed: 5 }}
							on:introend={() => {
								showOccupation = true;
								setTimeout(() => {
									typeOccupation = false;
									showOccupation = false;
								}, 3000);
							}}
							on:outroend={() => (typeOccupation = true)}>David.occupation</span
						>
					{/if}
				</span>
			</div>
			<div class:hidden={!showOccupation} class="occupation output">["Software Engineer"]</div>
		</li>
	</ul>
</div>

<style lang="css">
	.console-top {
		display: flex;
		align-items: center;
		height: 20px;
		background: lightgray;

		padding: 5px 0px 5px 10px;
		border-top-right-radius: 10px;
		border-top-left-radius: 10px;
	}

	.fake-icon {
		height: 10px;
		width: 10px;
		border: 1px solid gray;
		border-radius: 50%;
		margin-left: 10px;
	}

	.red-button {
		background-color: #ee6b5b;
	}
	.yellow-button {
		background-color: #f8be48;
	}
	.green-button {
		background-color: #5fc352;
	}

	.console-bottom {
		background-color: #483f4e;
		padding: 20px;
		border-bottom-right-radius: 5px;
		border-bottom-left-radius: 5px;
		box-shadow: 0px 5px 15px 2px #888888;

		letter-spacing: 2px;
	}

	.console-bottom li {
		color: #f9f9f9;
		margin-top: 30px;
	}

	.console-bottom li:first-of-type {
		margin-top: 15px;
	}
	.console-bottom li:last-of-type {
		margin-bottom: 15px;
		height: 40px;
	}

	.output {
		color: #ffcd64;
	}

	.output > a {
		text-decoration: none;
		color: #abb1ff;
	}
	.output > a:active {
		color: #a8dcdc;
	}

	.arrow {
		margin-right: 10px;
	}

	.hidden {
		visibility: hidden;
	}
</style>

// src/components/about.jsx
import React from "react";
import { Link } from "react-router-dom";
import { TypeAnimation } from "react-type-animation";

class About extends React.Component {
  constructor(props) {
    super(props);

    this._isMounted = false;

    this.state = {
      showOccupation: false
    };
    this.updateState = this.updateState.bind(this);
    this.sleepyUpdate = this.sleepyUpdate.bind(this);
  }

  componentDidMount() {
    this._isMounted = true;
  }

  componentWillUnmount() {
    this._isMounted = false;
  }

  updateState(bool) {
    if (this._isMounted) {
      this.setState({ showOccupation: bool });
    }
  }

  sleepyUpdate() {
    setTimeout(() => this.updateState(false), 2500);
  }

  showOccupation() {
    if (this.state.showOccupation) {
      return `["Software Engineer"]`;
    }
    return null;
  }

  render() {
    return (
      <div className="about-container">
        <div className="console-top">
          <div className="red-button fake-icon"></div>
          <div className="yellow-button fake-icon"></div>
          <div className="green-button fake-icon"></div>
        </div>
        <ul className="console-bottom">
          <li
            className="resume"
            key={"resume"}
          >
            <div className="resume input">
              <span className="arrow">></span>David.resume
            </div>
            <div className="resume output">
              ["<Link to="/resume">Resume</Link>"]
            </div>
          </li>

          <li
            className="education"
            key={"education"}
          >
            <div className="education input">
              <span className="arrow">></span>David.education
            </div>
            <div className="education output">
              [" B.A. Geography - University of California Los Angeles", "Self
              Study - App Academy Full Stack Bootcamp"]
            </div>
          </li>

          <li
            className="tech"
            key={"tech"}
          >
            <div className="tech input">
              <span className="arrow">></span>David.techStack
            </div>
            <div className="tech output">
              ["HTML", "CSS", "Javascript", "Typescript", "React", "Redux",
              "Node", "PostgreSQL", "Docker", "AWS", "Python", "Ruby", "Rails",
              "GIS"]
            </div>
          </li>

          <li
            className="interests"
            key={"interests"}
          >
            <div className="interests input">
              <span className="arrow">></span>David.interests
            </div>
            <div className="interests output">
              ["Skateboarding", "Rock Climbing", "League of Legends", "Running"]
            </div>
          </li>

          <li className="contact-info">
            <div className="contact-info input">
              <span className="arrow">></span>David.contactInfo
            </div>
            <div className="contact-info output">
              ["
              <a
                href="mailto:me@daviddixon.io"
                target="_blank"
                alt="email address"
                rel="noopener"
              >
                me@daviddixon.io
              </a>
              ", "
              <a
                href="https://www.linkedin.com/in/david-d-b36589190/"
                target="_blank"
                alt="linkedin link"
                rel="noopener"
              >
                LinkedIn
              </a>
              ", "
              <a
                href="https://github.com/chimichanga-dd"
                target="_blank"
                alt="github link"
                rel="noopener"
              >
                GitHub
              </a>
              "]
            </div>
          </li>

          <li
            className="occupation"
            key={"occupation"}
          >
            <div className="occupation input">
              <span className="arrow">></span>
              <TypeAnimation
                sequence={[
                  () => {
                    this.updateState(false);
                  },
                  "David.Occupation",
                  0,
                  () => {
                    this.updateState(true);
                  },
                  "David.Occupation",
                  3700,
                  () => {
                    this.updateState(false);
                  },
                  "",
                  0
                ]}
                repeat={Infinity}
                deletionSpeed={99}
              />
            </div>
            <div className="occupation output">{this.showOccupation()}</div>
          </li>
        </ul>
      </div>
    );
  }
}

export default About;
