// src/components/portfolio.jsx

import React from "react"
import Nav from "./nav"
import Welcome from "./welcome"
import About from "./about"
import Projects from "./projects"
import Contact from "./contact"



class portfolio extends React.Component{

    render(){
        return(
            <div className="portfolio">
                <Nav />
                <Welcome />
                <About />
                <Projects />
                <Contact />
            </div>
        )
    }
    
}

export default portfolio

// src/components/portfolio.svelte
<script>
	import Nav from './nav.svelte';
	import Welcome from './welcome.svelte';
	import About from './about.svelte';
	import Projects from './projects.svelte';
	import Contact from './contact.svelte';
</script>

<div class="portfolio">
	<Nav />
	<Welcome />
	<About />
	<Projects />
	<Contact />
</div>

<style lang="css">
	.portfolio {
		max-width: 900px;
		padding: 20px;
		margin: 0 auto;
	}
</style>
